# This workflow automatically builds static files with Dockerfile and deploys them to GitHub Pages
# whenever something is pushed / merged into main branch

name: Pages build and deployment CI/CD

on:
  push:
    # this will trigger when pushing to main but also when merging PR
    branches: [main]

jobs:
  job-1:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build --file Dockerfile --tag builder-image .

      - name: Run the Docker image to build static files
        run: docker run --name builder-container builder-image

      - name: Extract static files from the Docker container
        run: docker cp builder-container:/app/dist .

      - name: Upload static files artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
          name: github-pages

  job-2:
    name: Deploy
    needs: job-1
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment.
    # Make sure to switch deployment source to GitHub Actions in:
    #   Settings -> Pages -> Build and deployment -> Source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
